Django_level_four/learning_templates/basicapp/urls.py
from django.urls import path

from . import views

#TEMPLATE TAGGING
app_name = 'basicapp'

urlpatterns = [
path('relative/',views.relative,name='relative'),
path('other/',views.other,name='other'),

]

Django_level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.urls import include


urlpatterns = [
    path('', views.index,name="index"),
    path('basicapp/', include('basicapp.urls')),
    path('admin/', admin.site.urls),

]

Django_level_four/learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

Django_level_four/learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

Django_level_four/learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li ><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li ><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li ><a class="navbar-link" href="{% url 'basicapp:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
<div class="container">
  {% block body_block %}

  {% endblock %}

</div>


  </body>
</html>

Django_level_four/learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
    <h1>Hi Index</h1>
    <h1>{{ text|cut:'hello'|upper }}
    {{number|add:"20"}}</h1>

{% endblock %}

Django_level_four/learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>Yo Other</h1>

{% endblock %}

Django_level_four/learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> Hello Ugly Baby</h1>
    <a href="{% url 'basicapp:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'index' %}">Index</a>

  </body>
</html>